// todo-vue/src/components/TodoList.vue
<template>
  <div class="todo-list">
    <TodoItem
      v-for="todo in todoLists"
      :key="todo.key"
      :id="todo.id"
      :contents="todo.contents"
      :done="todo.done"
      :hide="todo.hide"
    />
  </div>
</template>

<script>
import TodoItem from "./TodoItem.vue";

export default {
  name: "TodoList",
  components: {
    TodoItem
  },
  props: {
    todos: Array
  },
  computed: {
    todoLists() {
      return this.todos;
    }
  }
};
</script>

// todo-typescript/src/components/TodoList.tsx
import React from "react";
import TodoItem from "./TodoItem";
import { useTodoState } from "../TodoContext";

function TodoList() {
    const todos = useTodoState();
    type TodoType = { id: number; contents: string; done: boolean; hide: boolean }

    return (
        <div>
            {todos.map((todo: TodoType) => (
                <TodoItem
                    key={todo.id}
                    id={todo.id}
                    contents={todo.contents}
                    done={todo.done}
                    hide={todo.hide}
                />
            ))}
        </div>
    );
}

export default React.memo(TodoList);
